x-common-env: &common-env
  SECRET: "esta_es_mi_compleja_clave_secreta"

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "9090:9090"
    environment:
      <<: *common-env
    depends_on:
      - cines-service
      - funciones-service
      - peliculas-service
      - salas-service
      - usuarios-service
      - fidelizacion-service
      - notificacion-service
      - empleados-service

  usuarios-service:
    build: ./usuarios-service
    ports:
      - "9091:9091"
    environment:
      <<: *common-env

  peliculas-service:
    build: ./peliculas-service
    ports:
      - "9092:9092"
    environment:
      <<: *common-env

  cines-service:
    build: ./cines-service
    ports:
      - "9093:9093"
    environment:
      <<: *common-env

  salas-service:
    build: ./salas-service
    ports:
      - "9094:9094"
    environment:
      <<: *common-env

  funciones-service:
    build: ./funciones-service
    ports:
      - "9095:9095"
    environment:
      <<: *common-env

  fidelizacion-service:
    build: ./fidelizacion-service
    ports:
      - "9096:9096"
    environment:
      <<: *common-env

  notificacion-service:
    build: ./notificacion-service
    ports:
      - "9098:9098"
    environment:
      <<: *common-env

  empleados-service:
    build: ./empleados-service
    ports:
      - "9099:9099"
    environment:
      <<: *common-env

  confiteria-service:
    build: ./confiteria-service
    ports:
      - "9060:9060"
    environment:
      <<: *common-env

  pago-service:
    build: ./pago-service
    ports:
      - "9097:9097"
    environment:
      <<: *common-env