server:
  port: 9090

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: usuarios-service
              uri: http://usuarios-service:9091
              predicates:
                - Path=/usuarios/**

            - id: peliculas-service
              uri: http://peliculas-service:9092
              predicates:
                - Path=/peliculas/**

            - id: cines-service
              uri: http://cines-service:9093
              predicates:
                - Path=/cines/**

            - id: salas-service
              uri: http://salas-service:9094
              predicates:
                - Path=/salas/**

            - id: funciones-service
              uri: http://funciones-service:9095
              predicates:
                - Path=/funciones/**,/entradas/**

            - id: confiteria-service
              uri: http://confiteria-service:9060
              predicates:
                - Path=/confiteria/**

            - id: pago-service
              uri: http://pago-service:9097
              predicates:
                - Path=/pagos/**