server:
  port: 9090

spring:
  main:
      web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: usuarios-service
            uri: http://localhost:9091
            predicates:
            - Path=/usuarios/**

          - id: peliculas-service
            uri: http://localhost:9092
            predicates:
            - Path=/peliculas/**

          - id: cines-service
            uri: http://localhost:9093
            predicates:
            - Path=/cines/**

          - id: salas-service
            uri: http://localhost:9094
            predicates:
            - Path=/salas/**

          - id: funciones-service
            uri: http://localhost:9095
            predicates:
            - Path=/funciones/**,/entradas/**
