spring.application.name=funciones-service
server.port=9095

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/bd_funciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

api.base-url=http://api-gateway:9090
api.sala.exists=/salas/%d/exists
api.pelicula.exists=/peliculas/%d/exists
api.usuario.exists=/usuarios/%d/exists
api.funcion.exists=/funciones/%d/exists

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.file.name=logs/funciones-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
